version: "3.9"
services:
    database:
        image: postgres
        environment:
            POSTGRES_USER: php
            POSTGRES_PASSWORD: php
            POSTGRES_DB: cars_reservation
        ports:
            - 5433:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        volumes:
            - ./docker/database:/var/lib/postgresql

    adminer:
        image: adminer
        restart: always
        ports:
            - 9090:8080
