version: "3.9"
services:
  database:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: deathcrush
      MYSQL_USER: php
      MYSQL_PASSWORD: php
      MYSQL_DATABASE: cars_reservation
    ports:
      - 3306:3306
    volumes:
      - ./docker/database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
